/* ============================================================
   CONTENT CONFIGURATION
   All text, images, and icons editable via editor.html
   ============================================================ */

/* Auto-generated by editor.html — paste into js/content.js */
window.CONTENT = {
  "meta": {
    "pageTitle": "Data for the Agentic Enterprise",
    "author": "Zanco Jaff and Evens Bonifasse",
    "preparedBy": "Prepared by Evens Bonfiasse"
  },
  "intro": {
    "kicker": "Unlock, Trust, Activate",
    "title": "Data for the Agentic Enterprise",
    "subtitle": "Every organization is investing in data to power AI and agents. This story shows how <strong>MuleSoft</strong>, <strong>Informatica</strong> and <strong>Salesforce</strong> work together to get data right.",
    "chips": [
      {
        "label": "Unlock",
        "cssClass": "chip-unlock"
      },
      {
        "label": "Trust",
        "cssClass": "chip-trust"
      },
      {
        "label": "Activate",
        "cssClass": "chip-activate"
      }
    ],
    "story": [
      "<strong>Every enterprise has data. Very few have understanding.</strong> Shipper data is scattered across CRM, ERP, marketing platforms, support tools, and legacy systems. As this data moves across the enterprise, it loses meaning. Identifiers change, definitions drift, and governance fragments.",
      "To see how this impacts the business, let's look at a specific scenario. While this journey applies to any domain—whether it's a product, supplier, or asset—we'll explore a <strong>Shipper example</strong> to illustrate the impact.",
      "Meet <strong>Robert</strong>. He's a loyal, high‑value shipper — yet Sales sees one version of him, Finance sees another, and Support has no history. To fix these inconsistent experiences, enterprises must <strong>Unlock</strong> data from silos, ensure it is <strong>Trusted</strong>, and <strong>Activate</strong> it in the flow of work.",
      "This infographic shows how you transform fragmented data into coordinated action — and why agents only work when they have trusted context."
    ],
    "storyEmphasisIndex": 3,
    "pillars": [
      {
        "title": "1) Unlock",
        "logos": [
          {
            "src": "https://www.vectorlogo.zone/logos/mulesoft/mulesoft-ar21.svg",
            "alt": "MuleSoft logo"
          },
          {
            "src": "https://www.vectorlogo.zone/logos/informatica/informatica-ar21.svg",
            "alt": "Informatica logo"
          }
        ],
        "body": "<strong>Connect, Integrate, Understand.</strong> Making data available and understandable where it's needed across APIs, apps, and legacy systems.",
        "logoTags": []
      },
      {
        "title": "2) Trust",
        "logos": [
          {
            "src": "https://www.vectorlogo.zone/logos/informatica/informatica-ar21.svg",
            "alt": "Informatica logo"
          }
        ],
        "body": "<strong>Validate, Protect, Unify.</strong> Making data accurate, consistent, and defensible. <strong>Informatica</strong> governs and masters customer data to establish a trusted \"Golden Record.\"",
        "logoTags": []
      },
      {
        "title": "3) Activate",
        "logos": [
          {
            "src": "https://www.vectorlogo.zone/logos/salesforce/salesforce-ar21.svg",
            "alt": "Salesforce logo"
          },
          {
            "src": "https://www.vectorlogo.zone/logos/mulesoft/mulesoft-ar21.svg",
            "alt": "MuleSoft logo"
          }
        ],
        "logoTags": ["Data 360", "Agent Fabric"],
        "body": "<strong>Decide, Orchestrate, Act.</strong> Using trusted data to drive outcomes. <strong>Salesforce Data 360</strong> , <strong>Agentforce</strong> and <strong>Agent Fabric</strong> turn context into autonomous decisions in the flow of work."
      }
    ],
    "note": "You'll see this journey step‑by‑step, using one shipper story — moving from data chaos through Unlocking, Trusting, and Activating for agent‑driven execution.",
    "startBtn": "▶ Start the Story",
    "backBtn": "← Introduction"
  },
  "storyHeader": {
    "title": "Customer 360",
    "titleHL": "Story",
    "subtitle": "From {chaos} to {trust} to {context} to {action}.",
    "navWords": {
      "chaos": "Chaos",
      "trust": "Trust",
      "context": "Context",
      "action": "Action"
    }
  },
  "chapters": [
    {
      "id": 1,
      "title": "Chapter 1: Data Chaos",
      "chipLabel": "Unlock",
      "chipClass": "chip-unlock",
      "tagline": "Silos create chaos — no shared customer truth.",
      "subtitle": "Everyone has data. No one has the full picture.",
      "body": [
        "In every enterprise, customer data lives everywhere — <strong>but never together</strong>.",
        "<strong>Sales</strong> has one view. <strong>Marketing</strong> has another. <strong>Finance</strong>, <strong>Support</strong>, and <strong>legacy systems</strong> each hold their own version of \"truth\".",
        "Each system is built to do its job well — <strong>not</strong> to agree with the others."
      ],
      "infoBox": {
        "title": "What this looks like in practice",
        "intro": "Meet <strong>Robert</strong>. He appears differently in every system:",
        "items": [
          "<strong>SAP S/4 Hana:</strong> Billing account + contract value (ID: 101)",
          "<strong>Salesforce CRM:</strong> Billing account + contract value (ID: 111)",
          "<strong>Marketing Cloud:</strong> Batch incident comms — no linked identity",
          "<strong>IBM Mainframe:</strong> Years of history that's hard to access",
          "<strong>Databricks:</strong> Shipment Events  (ID: 202)",
          "<strong>Service Cloud:</strong> Open incidents ( ID:234)"
        ]
      },
      "infoBox2": {
        "title": "The hidden cost",
        "items": [
          "Service Cloud treats a 20-year VIP shipper like a first-time caller\n",
          "Sales misses revenue signals locked in mainframe ops history\n",
          "Marketing sends rail shortage alerts to every shipper — not just impacted ones\n",
          "MuleSoft moves this fragmented data faster — amplifying the inconsistency at scale\n"
        ]
      },
      "closingQ": "The journey starts by answering one question:",
      "closingAns": "Can the enterprise agree on <strong>who the customer is</strong> — and what's true <strong>right now</strong>?"
    },
    {
      "id": 2,
      "title": "Chapter 2. Establishing Truth",
      "chipLabel": "Trust",
      "chipClass": "chip-trust",
      "tagline": "Informatica creates the Golden Record — trust at scale.",
      "subtitle": "Why the Golden Record is Essential",
      "body": [
        "In Chapter 1, we saw the cost of fragmentation. To drive <strong>revenue growth</strong> and <strong>optimise costs</strong>, the business needs a unified 360-degree view. This <strong>Golden Record</strong> is not just data cleanup; it powers critical strategies like exceptional <em>Customer Experience</em> and <em>Finance Transformation</em>, ensuring every department acts on the same trusted facts.",
        "To create a Golden Record, we must look inside the <strong>Informatica MDM Hub</strong>. It follows a rigorous <strong>4-step logic pipeline</strong> powered by the <strong>CLAIRE AI Engine</strong>:"
      ],
      "pipelineSteps": [
        {
          "num": "1.",
          "numClass": "text-slate-400",
          "title": "Ingest (Smart Mapping)",
          "desc": "CLAIRE automatically identifies source fields and maps them to master data models."
        },
        {
          "num": "2.",
          "numClass": "text-brightCyan",
          "title": "Cleanse &amp; Enrich",
          "desc": "Validates data quality rules and standardizes shipper attributes."
        },
        {
          "num": "3.",
          "numClass": "text-energeticOrange",
          "title": "Match (AI-Powered)",
          "desc": "Combines rule-based methods with supervised learning to refine matching precision."
        },
        {
          "num": "4.",
          "numClass": "text-green-600",
          "title": "Survive (Trust Framework)",
          "desc": "The Trust Framework picks the best value for each field based on source reliability."
        }
      ],
      "result": "A \"Best Version of Truth\" is minted. Permanent ID: <strong>E-999</strong>."
    },
    {
      "id": 3,
      "title": "Chapter 3. Data Democratisation &amp; Write-back",
      "chipLabel": "Trust",
      "chipClass": "chip-trust",
      "tagline": "Share the truth everywhere — operational + analytic consistency.",
      "body": [
        "Creating the Golden Record is only half the battle. To drive business value, we must achieve <strong>Data Democratisation</strong>—ensuring this single source of truth is instantly accessible to every system and user that needs it, from the front office to the back office."
      ],
      "shareStrategy": {
        "title": "The \"Share &amp; Consume\" Strategy:",
        "intro": "Informatica transforms MDM from a \"vault\" into a \"hub\" that fuels the enterprise:",
        "items": [
          "<strong>Operational Write-back:</strong> The system actively pushes the new ID (E-999) and trusted attributes <em>back</em> to the sources (SAP, Salesforce). This aligns operations, ensuring Sales and Finance see the exact same customer.",
          "<strong>Analytical Consumption:</strong> As visualized with <strong>Data Platforms</strong>, governed master data is made available for analytics. Business analysts can now \"consume\" trusted data immediately, without spending weeks cleaning it first."
        ]
      },
      "robertStory": "Robert's Reality: The Shipper \"VIP\" status from the IBM mainframe is no longer hidden. It has been written back to his profile in Salesforce, so the Sales Rep knows exactly who they are talking to.",
      "subtitle": ""
    },
    {
      "id": 4,
      "title": "Chapter 4. Intelligent Orchestration",
      "chipLabel": "Unlock",
      "chipClass": "chip-unlock",
      "tagline": "Orchestrate processes — APIs turn trusted data into outcomes.",
      "body": [
        "With the Golden Record established, <strong>MuleSoft</strong> becomes the <strong>middleware layer</strong> that standardizes how applications connect. Instead of building brittle point‑to‑point integrations, teams expose and consume <strong>reusable APIs</strong> — so systems can participate in a shared process <em>without changing their existing interfaces</em>."
      ],
      "muleBox": {
        "title": "What MuleSoft is doing here (in plain terms)",
        "items": [
          "<strong>Decouples systems:</strong> each application keeps its contract; MuleSoft provides a consistent API layer on top.",
          "<strong>Standard connectivity:</strong> the same patterns apply across SAP, Salesforce, legacy (IBM), and any partner app.",
          "<strong>Less complexity over time:</strong> new channels and processes reuse APIs instead of adding more custom code.",
          "<strong>Streamlining implementation and API consumption::</strong> Convert intricate system APIs into standardized process APIs, enabling developers to utilize them independently of subject matter expertise."
        ]
      },
      "robertStory": {
        "title": "Robert's Story: Orchestrating a Weather Delay Incident",
        "intro": "A weather event disrupts <strong>Robert Smith's</strong> active shipments on the Toronto to Montreal corridor. MuleSoft orchestrates the response across CN's systems using APIs — while each application stays unchanged.",
        "items": [
          "<strong>Shipment history (IBM Mainframe):</strong> An API retrieves Robert's VIP Shipper status and all active shipments on the impacted route.",
          "<strong>Incident management (Service Cloud):</strong> A delay ticket is opened and linked to the correct shipper record automatically.",
          "<strong>Targeted communications (Marketing Cloud):</strong> Targeted Alerts  -  These alerts are exclusively for Shippers within the Toronto-Montreal route, ensuring relevant communication instead of a general broadcast.",
          "<strong>Outcome visibility (Salesforce CRM):</strong> Sales and service teams see real-time delay status instantly. One view, every team."
        ]
      },
      "subtitle": ""
    },
    {
      "id": 5,
      "title": "Chapter 5. Analytics &amp; Insight",
      "chipLabel": "Trust",
      "chipClass": "chip-trust",
      "tagline": "Make data usable for people and AI — without manual wrangling.",
      "body": [
        "In this chapter, the goal is simple: turn trusted enterprise data into insights that teams can actually use. Instead of stitching together exports and spreadsheets, Informatica makes the analytics path repeatable and reliable."
      ],
      "buildingBlocks": {
        "title": "Three \"Data\" building blocks",
        "items": [
          "<strong>Data Catalog</strong> helps people find the right data fast — with clear names, meaning, and where it came from.",
          "<strong>Data Integration</strong> builds pipelines with low-code / no-code — faster than scripting, easier to change, and easier to debug.",
          "<strong>Data Quality</strong> applies consistent checks and standardization so the numbers can be trusted."
        ],
        "metadata": "These capabilities are <strong>metadata-driven</strong> — they share the same \"data about the data,\" so they can understand and reinforce each other (lineage, rules, mappings, and business meaning stay connected).",
        "snowflake": "And when Snowflake is your analytics engine, Informatica can use <strong>pushdown optimization</strong> — executing transformations (and many quality rules) directly in Snowflake, so Snowflake does the heavy lifting at scale."
      },
      "snowflakeNote": "On the right, Databricks is where teams analyze and explore at scale - while Informatica ensures what lands there is discoverable, governed, and ready for decisions.",
      "robertStory": {
        "title": "Robert's Story: The Insight",
        "body": "Analysts in Databricks and Tableau can finally connect the dots. They see Robert's 20-year shipping loyalty trend ( IBM Legacy Mainframe) alongside his recent shipment activity (Databricks) and Incident communication (Salesforce Marketing Cloud). The insight is clear: <em>\"Robert is not just a good customer; he is a VIP shipper at risk of churn due to a process error.\"</em>"
      },
      "closing": "<strong>Databricks</strong> (Right Column) then aggregates this governed history. We use <strong>Cloud Data\nIntegration (CDI)</strong> and <strong>Cloud Data Quality (CDQ)</strong> to transform and validate data natively on Databricks (ELT), ensuring the analytical foundation is solid. This is empowered by <strong>Cloud Data\nGovernance and Catalog (CDGC)</strong>, which combines governance, catalog, and data quality\ncapabilities into a singular tool for automating data intelligence insights. <strong>Tableau </strong> applies business semantics, aligns KPIs across teams, surfaces patterns and anomalies.\n\n",
      "subtitle": ""
    },
    {
      "id": 6,
      "title": "Chapter 6. Activation &amp; Operationalisation",
      "chipLabel": "Activate",
      "chipClass": "chip-activate",
      "tagline": "Data 360 turns trusted data into contextual, real-time profiles.",
      "body": [
        "<strong>Salesforce Data 360</strong> is the pre-built, pre-integrated activation layer specialised for Salesforce apps and the wider enterprise. Through <span class=\"harmonisation-glow\">Harmonisation</span>, data from multiple systems is linked into a connected customer model. This keeps the context intact and enables a trusted Customer 360 view."
      ],
      "contextBox": {
        "title": "Context &amp; Trust:",
        "intro": "Data 360 is not only creating an ID graph; it maps engagement data and natively makes it available for Salesforce to run its processes, including <strong>Agentforce</strong>.",
        "items": [
          "<strong>Pre-built Canonical Model:</strong> Data 360 captures complex entity relationships out-of-the-box.",
          "<strong>Domain Specialisation:</strong> It creates a specialised foundation for Customer (B2B/B2C) operations, ensuring every app speaks the same language."
        ],
        "result": "Operational scale for Salesforce applications and beyond."
      },
      "robertStory": {
        "title": "Robert's Story: The Activation",
        "body": "Robert's profile is no longer a static record buried in a legacy database; it is now a live, API-ready asset. His \"VIP Shipper\" status and Active Lane Disruptions are unified into a single graph (UUID123) that is instantly available to the Service Agent’s console and the Agentforce autonomous agent. The data is now <em>operational</em>.. "
      },
      "subtitle": ""
    },
    {
      "id": 7,
      "title": "Chapter 7. The Agentic Future",
      "chipLabel": "Activate",
      "chipClass": "chip-activate",
      "tagline": "Agentforce uses context to act — safely and autonomously.",
      "body": [
        "<strong>From Insights to Autonomous Action.</strong> Data 360 provides the critical <em>Context</em> that allows the <strong>Agentforce Agent</strong> to act autonomously.",
        "<strong>Salesforce Agentforce</strong> is the agent layer that can plan and take actions across Salesforce experiences — grounded in the live customer context from Data 360. It acts through governed workflows and policies, so outcomes stay consistent and auditable."
      ],
      "robertStory": {
        "title": "Robert's Story: Autonomous Resolution",
        "intro": "Robert calls support about the status of a delayed shipment. An Agentforce Agent answer.",
        "items": [
          "<strong>Context (Data 360):</strong> the agent immediately sees \"20‑Year VIP Shipper\" status.\n",
          "<strong>Decision:</strong> it proactively chooses to waive the delay penalty based on CN’s VIP policy.\n",
          "<strong>Action:</strong> it creates a case in Service Cloud, updates the account in Sales Cloud, triggers a targeted Marketing Alert to Robert with full rationale captured.\n"
        ]
      },
      "subtitle": ""
    },
    {
      "id": 8,
      "title": "Chapter 8. Enterprise Action Fabric (Beyond Salesforce)",
      "chipLabel": "Activate",
      "chipClass": "chip-activate",
      "tagline": "Close the loop — insights become action, and action becomes learning.",
      "body": [
        "<strong>Agentforce can act inside Salesforce.</strong> To take trusted, contextual action across the wider enterprise, we extend the agentic layer with <strong>MuleSoft Agent Fabric</strong>."
      ],
      "muleBox": {
        "title": "What MuleSoft adds in Chapter 8",
        "items": [
          "<strong>Agent-ready APIs:</strong> wrap existing services so agents can safely call them.",
          "<strong>Governance:</strong> enforce auth, scopes, rate limits, and audit consistently.",
          "<strong>Orchestration:</strong> coordinate multi-step actions across systems inside and outside the enterprise."
        ]
      },
      "evolutionBox": {
        "title": "How the story evolves beyond the CRM",
        "intro": "At this point, Robert's issue is resolved <strong>inside Salesforce</strong>. Now the same agentic flow can coordinate work <strong>across the enterprise</strong> — and even <strong>outside the enterprise</strong> — without losing trust or context.",
        "items": [
          "<strong>Inside the enterprise:</strong> trigger credit holds in ERP, update entitlements, open IT/service tasks, and confirm inventory — all through governed APIs.",
          "<strong>Outside the enterprise:</strong> coordinate with partners (logistics, payments, resellers, field service) via secure integrations so the customer experience stays seamless end‑to‑end.",
          "<strong>Orchestrated agents:</strong> Agentforce decides <em>what</em> should happen; MuleSoft coordinates <em>how</em> it happens across systems, teams, and partners."
        ],
        "result": "one trusted customer story, one contextual decision, many coordinated actions — everywhere they need to happen."
      },
      "closing": {
        "title": "Closing thought",
        "body": "<strong>Trusted data enables context. Context enables agents.</strong> Without trust, autonomy scales mistakes.",
        "contact": "Any questions? Contact <a href=\"mailto:ebonifasse@salesforce.com\">Evens Bonifasse</a>"
      },
      "subtitle": ""
    }
  ],
  "sourceCards": [
    {
      "id": "src-sap",
      "borderClass": "border-slate-500",
      "label": "SAP",
      "icon": "https://cdn.brandfetch.io/sap.com?c=1idycWZwgN4U02bYNNr",
      "iconAlt": "SAP logo",
      "badge": "Holds: Billing + Contract Value",
      "eid": "ID: 101",
      "tooltip": {
        "title": "SAP ERP",
        "body": "Enterprise resource planning system handling finance, billing, and order management."
      }
    },
    {
      "id": "src-sfdc",
      "borderClass": "border-blue-500",
      "label": "SFDC",
      "icon": "https://cdn.brandfetch.io/salesforce.com?c=1idycWZwgN4U02bYNNr",
      "iconAlt": "Salesforce logo",
      "badge": "Holds: Opps + Accnt",
      "eid": "ID: A99",
      "tooltip": {
        "title": "Salesforce CRM",
        "body": "Customer Relationship Management system managing sales opportunities and accounts."
      }
    },
    {
      "id": "src-mkto",
      "borderClass": "border-purple-500",
      "label": "Marketing Cloud",
      "icon": "https://cdn.brandfetch.io/salesforce.com?c=1idycWZwgN4U02bYNNr",
      "iconAlt": "Marketing Cloud logo",
      "badge": "Holds: Incident comms",
      "eid": "ID: 500",
      "tooltip": {
        "title": "Marketing cloud",
        "body": "Marketing automation platform tracking user engagement and campaigns."
      }
    },
    {
      "id": "src-snow",
      "borderClass": "border-green-600",
      "label": "Databricks",
      "icon": "https://cdn.brandfetch.io/databricks.com?c=1idycWZwgN4U02bYNNr",
      "iconAlt": "Databricks",
      "badge": "Holds: Shipment Events",
      "eid": "ID: 202",
      "tooltip": {
        "title": "Databricks",
        "body": "Databricks platform contains Shipment Events."
      }
    },
    {
      "id": "src-legacy",
      "borderClass": "border-slate-700",
      "label": "IBM Mainframe",
      "icon": "https://cdn.brandfetch.io/ibm.com?c=1idycWZwgN4U02bYNNr",
      "iconAlt": "IBM logo",
      "badge": "Holds: Shipment & ops history",
      "eid": "ID: 800",
      "tooltip": {
        "title": "IBM Mainframe",
        "body": "Historical system of record containing long-term customer shipment & ops history."
      }
    }
  ],
  "sourceContextTooltip": {
    "title": "Transactional Sources: The Silos",
    "body": "These systems are <em>specialists</em> (e.g., SAP for Finance, Salesforce for CRM). Each maintains its own disconnected record (e.g., SAP Cust #101 vs. SFDC ID A99), creating the fragmentation problem."
  },
  "muleCard": {
    "icon": "https://cdn.brandfetch.io/mulesoft.com?c=1idycWZwgN4U02bYNNr",
    "iconAlt": "MuleSoft logo",
    "label": "MuleSoft",
    "sublabel": "Orchestration",
    "fabricTitle": "Enterprise Agent Fabric",
    "fabricItems": [
      "Catalogue <strong>MCP Servers</strong> &amp; Agents into a single repository to provide actions to Agentforce",
      "<strong>Governance &amp; Security:</strong> visualize, categorize, and enforce strict security rules",
      "Orchestrate multiple agents together into one unified <strong>Super Agent</strong>"
    ],
    "tooltip": {
      "title": "MuleSoft",
      "body": "Integration platform connecting applications via APIs to orchestrate business processes."
    },
    "labelAppInt": "App Integration"
  },
  "dataManagement": {
    "groupLabel": "Data Management",
    "groupIcon": "https://cdn.brandfetch.io/informatica.com?c=1idycWZwgN4U02bYNNr",
    "groupIconAlt": "Informatica logo",
    "catalog": {
      "label": "DATA CATALOG",
      "sublabel": "Scan &amp; Discover",
      "tooltip": {
        "title": "Informatica Catalog",
        "body": "Scans and indexes technical metadata to provide business context and make data discoverable."
      }
    },
    "integration": {
      "label": "DATA INTEGRATION",
      "sublabel": "ETL / ELT",
      "tooltip": {
        "title": "Cloud Data Integration",
        "body": "Connects disparate data sources and applications across multi-cloud and hybrid environments."
      }
    },
    "quality": {
      "label": "DATA QUALITY",
      "sublabel": "Cleanse &amp; Rules",
      "tooltip": {
        "title": "Data Quality",
        "body": "Standardizes, validates, and cleanses data to ensure trust and accuracy for downstream use."
      }
    },
    "mdm": {
      "hubLabel": "MDM Hub",
      "tooltip": {
        "title": "Multidomain MDM",
        "what": "A single platform to manage multiple domains (Customer, Product, Supplier) of data.",
        "func": "Consolidates data from silos, resolves duplicates, masters the \"Golden Record,\" and enforces governance."
      },
      "pipeline": [
        {
          "id": "pipe-1",
          "icon": "📥",
          "title": "Ingest",
          "sub": "Smart Map"
        },
        {
          "id": "pipe-2",
          "icon": "🧹",
          "title": "Cleanse",
          "sub": "Quality"
        },
        {
          "id": "pipe-3",
          "icon": "🔗",
          "title": "Match",
          "sub": " AI/ML"
        },
        {
          "id": "pipe-4",
          "icon": "⚖️",
          "title": "Survive",
          "sub": "Trust"
        },
        {
          "id": "pipe-5",
          "icon": "",
          "title": "GOLDEN RECORD E-999",
          "sub": ""
        }
      ]
    }
  },
  "analytics": {
    "labelAnalytics": "Analytics &amp; Share",
    "snowflakeCard": {
      "icons": [
        {
          "src": "https://cdn.brandfetch.io/databricks.com?c=1idycWZwgN4U02bYNNr",
          "alt": "Databricks logo"
        },
        {
          "src": "",
          "alt": "test"
        }
      ],
      "label": "Data Platforms",
      "sublabel": "Zero Copy",
      "tooltip": {
        "title": "Data Platforms",
        "body": "Unified platforms for data warehousing, data lakes, and data sharing without moving data."
      }
    },
    "tableauCard": {
      "icon": "https://cdn.brandfetch.io/tableau.com?c=1idycWZwgN4U02bYNNr",
      "iconAlt": "Tableau Logo",
      "label": "Tableau",
      "tooltip": {
        "title": "Tableau",
        "body": "Visual analytics and BI platform."
      }
    }
  },
  "data360": {
    "icon": "https://cdn.brandfetch.io/salesforce.com?c=1idycWZwgN4U02bYNNr",
    "iconAlt": "Salesforce logo",
    "label": "Data 360",
    "desc": "Data 360 unifies disparate data into a scalable, domain-specialised foundation. It provides the <strong>trusted context (ID: E-999)</strong> essential for powering Agentforce and Salesforce apps.",
    "tooltip": {
      "title": "Salesforce Data 360",
      "body": "Activates trusted data to power customer experiences, AI, and analytics."
    },
    "graphCenter": {
      "topLabel": "Unified",
      "name": "Robert",
      "uuid": "UUID: 123",
      "linkedId": "Linked: E-999"
    },
    "graphNodes": [
      {
        "id": "g-sap",
        "icon": "https://cdn.brandfetch.io/sap.com?c=1idycWZwgN4U02bYNNr",
        "tableHead": "Inv#99",
        "style": "top: 30%; left: 3%;",
        "iconAlt": ""
      },
      {
        "id": "g-sfdc",
        "icon": "https://cdn.brandfetch.io/salesforce.com?c=1idycWZwgN4U02bYNNr",
        "tableHead": "Opp$50k",
        "style": "top: 30%; right: 5%;",
        "iconAlt": ""
      },
      {
        "id": "g-mkto",
        "icon": "https://cdn.brandfetch.io/salesforce.com?c=1idycWZwgN4U02bYNNr",
        "tableHead": "Incident Comms",
        "style": "bottom: 30%; left: 5%;",
        "iconAlt": ""
      },
      {
        "id": "g-snow",
        "icon": "https://cdn.brandfetch.io/databricks.com?c=1idycWZwgN4U02bYNNr",
        "tableHead": "Tkt#202",
        "style": "bottom: 15%; right: 20%;",
        "iconAlt": ""
      },
      {
        "id": "g-leg",
        "icon": "https://cdn.brandfetch.io/ibm.com?c=1idycWZwgN4U02bYNNr",
        "tableHead": "VIP 20y",
        "style": "top: 15%; right: 20%;",
        "iconAlt": ""
      }
    ]
  },
  "agentforce": {
    "icon": "https://wp.sfdcdigital.com/en-us/wp-content/uploads/sites/4/2025/10/agent-astro.webp?resize=2048,2048",
    "iconAlt": "Agent Astro",
    "label": "Agentforce",
    "atlasLabel": "Atlas Engine",
    "trustLabel": "Trust",
    "tooltip": {
      "title": "Agentforce Architecture",
      "atlasEngine": "The brain that plans and executes.",
      "trustLayer": "Ensures safety and privacy.",
      "vendorUrl": "https://www.salesforce.com/agentforce",
      "vendorLabel": "Visit Vendor"
    },
    "channels": [
      {
        "icon": "🌐",
        "label": "Web",
        "title": "Web"
      },
      {
        "icon": "💬",
        "label": "Chat",
        "title": "Slack / Chat"
      },
      {
        "icon": "📱",
        "label": "Mobile",
        "title": "Mobile / CRM"
      },
      {
        "icon": "📞",
        "label": "Voice",
        "title": "Voice"
      },
      {
        "icon": "✉️",
        "label": "Email",
        "title": "Email"
      }
    ],
    "channelLabel": "Channels",
    "autonomousZoneLabel": "Autonomous Zone (Context + Action)"
  },
  "sfApps": {
    "icon": "https://cdn.brandfetch.io/salesforce.com?c=1idycWZwgN4U02bYNNr",
    "iconAlt": "Salesforce logo",
    "label": "SALESFORCE CUSTOMER 360 APPS AND OTHER CN APPS",
    "apps": [
      {
        "icon": "☁️",
        "label": "Sales"
      },
      {
        "icon": "🎧",
        "label": "Service"
      },
      {
        "icon": "🎯",
        "label": "Marketing"
      },
      {
        "icon": "🛒",
        "label": "Commerce"
      },
      {
        "icon": "🧩",
        "label": "Other Apps"
      }
    ]
  },
  "agentforce2": {
    "icon": "https://cdn.brandfetch.io/mulesoft.com?c=1idycWZwgN4U02bYNNr",
    "iconAlt": "MuleSoft",
    "label": "Agent Fabric",
    "atlasLabel": "Any LLM, Agent and MCP Tools",
    "trustLabel": "Trust",
    "channelLabel": "Autonomous Zone (Context + Action)",
    "tooltip": {
      "title": "Agent Fabric Architecture",
      "atlasEngine": "The brain that coordinates, routes, secures and provide visibility into any Agent Action and Tools.",
      "trustLayer": "Ensures safety and privacy.",
      "vendorUrl": "https://www.salesforce.com/mulesoft/",
      "vendorLabel": "Visit Vendor"
    }
  }
};




